---

- name: install image-builder packages
  yum:
    name: "{{ item }}"
    state: present
  with_items:
    - "{{ image_builder_rpms }}"

- name: enable image-builder services
  systemd:
    name: "{{ item }}"
    state: started
    enabled: yes
  with_items:
    - "{{ image_builder_services }}"