---

- name: mount all file systems
  command: /usr/bin/mount -a
  
- name: create directory to download files
  file:
    path: "{{ download_dir }}"
    owner: root
    group: root
    mode: 0755
    state: directory

- name: download kernels source
  get_url:
    url: "{{ kernels_url}}/{{ item }}"
    dest: "{{ download_dir }}"
  retries: 3
  delay: 5
  ignore_errors: yes
  with_items:
    - "{{ kernels }}"

- name: untar kernels source on vdo volume
  command: "/usr/bin/tar zxf {{ download_dir }}/{{ item }} -C {{ vdo_mount_point }}"
  ignore_errors: yes
  with_items:
    - "{{ kernels }}"

- name: untar kernels source on non vdo volume
  command: "/usr/bin/tar zxf {{ download_dir }}/{{ item }} -C {{ no_vdo_mount_point }}"
  ignore_errors: yes
  with_items:
    - "{{ kernels }}"